### ISSUE TITLE
BnF Indien 327 satellite stanza

### ISSUE THREAD

**Issue by manufrancis** [TST-Project/paratexts#2]
This MS has 2 satellite stanzas on U2, f163v:

![image](https://user-images.githubusercontent.com/905870/203307722-156695fe-a48f-443c-a73e-698bff44eb45.png)

But on the satellite stanzas table the folio indicated is "folio 1r".

![image](https://user-images.githubusercontent.com/905870/203307878-add17045-8fb6-4483-8b7f-c2314885e8f8.png)

How come?

**Comment by chchch** [comment]
Ok, should be fixed now (...that's some pretty complicated markup you got there...)

**Comment by manufrancis** [comment]
looks fine!
Thanks!
